config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  resources :friends
  resources :users
  #get 'home/index'
  #root 'home#index'
  root 'friends#index'
  get 'abouts/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :friends
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/users.rb
class User < ApplicationRecord
end

app/models/users_login.rb
class UsersLogin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_employee!, except: [:index,:show]
  before_action :correct_employee, only: [:edit,:update,:destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
   # @friend = Friend.new
   @friend = current_employee.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.nw(friend_params)
    @friend = current_employee.friends.build(friend_params)  
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_employee
    $friend= current_employee.friends.find_by(id: params[:id]) 
    redirect_to friends_path, notice: "Your not authorized to edit this friend" if $friend.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :Twitter,:employee_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = user.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = user.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = user.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "user was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "user was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = user.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:First_name, :Last_name, :email, :phoneNumber)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/index.html.erb
<h1>This is about page<h1/>

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name,class:"form-control",placeholder: "first name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name,class:"form-control",placeholder: "last name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email,class:"form-control",placeholder: "email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone,class:"form-control",placeholder:"phone" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :Twitter,class:"form-control",placeholder:"Twitter" %>
  </div>
  <div class="field form-group">
    <%= form.number_field :employee_id,id: :friend_employee_id, class:"form-control",value:current_employee.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend,class:"btn btn-secondary" %> |

<td><%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>

<%= link_to 'Back', friends_path,class:"btn btn-secondary" %>

app/views/friends/index.html.erb
<%if employee_signed_in? %>
<table class ="table">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User ID</th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <%if friend.employee == current_employee%>
      <tr>
        <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.Twitter %></td>
        <td><%= friend.employee_id %></td>
        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path,class:"btn btn-secondary" %>
<%else %>
	<h1>Salame</h1>
	<p>Find me in app/views/home/index.html.erb</p>

<%end%>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead">  <%= @friend.email %> |  <%= @friend.phone %> | <%= @friend.Twitter %></p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%= link_to 'Edit', edit_friend_path(@friend),class:"btn btn-secondary" %> |
  <%= link_to 'Back', friends_path,class:"btn btn-secondary" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Salam_home' , root_path ,  class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
	  <%= link_to 'About' ,abouts_index_path, class:"nav-link" %>
        </li>
	<li class="nav-item">
	  <%= link_to 'New Friend' ,new_friend_path, class:"nav-link" %>
        </li>
	<%if employee_signed_in?%>
	   <li class="nav-item">
	     <%= link_to 'Sign out' ,destroy_employee_session_path, method: :delete, class:"nav-link" %>
       	   </li>
	   <li class="nav-item">
	     <%= link_to 'Edit Profile' , edit_employee_registration_path, class:"nav-link" %>
           </li>
	<%else %>
	  <li class="nav-item">
	    <%= link_to 'Sign UP' ,new_employee_registration_path, class:"nav-link" %>
          </li>
	  <li class="nav-item">
	    <%= link_to 'Sign in' ,new_employee_session_path, class:"nav-link" %>
          </li>
	<%end%>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Salame</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <p><% notice %> <%= flash[:notice] %><p>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Salam App</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
   <%= render 'home/header' %>
   <div class = "container">
	<br/>
    <% if notice %>
     <%= render 'layouts/alerts' %>
    <% end %>
    <br/>
     <%= yield %>
   </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :First_name %>
    <%= form.text_field :First_name, class:"form-control", placeholder:"First name" %>
  </div>

  <div class="field form-group">
    <%= form.label :Last_name %>
    <%= form.text_field :Last_name , class:"form-control", placeholder:"last name" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email ,class:"form-control", placeholder:"email" %>
  </div>

  <div class="field form-group">
    <%= form.label :phoneNumber %>
    <%= form.text_field :phoneNumber , class:"form-control", placeholder:"PhoneNumer" %>
  </div>
<br/>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<br/>
<%= render 'form', user: @user %>
<br/>
<%= link_to 'Show', @user, class:"btn btn-secondary" %>
<%= link_to 'Back', users_path, class:"btn btn-dark" %>

app/views/users/index.html.erb
<h1>users</h1>

<table class="table table-light table-striped">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.First_name %></td>
        <td><%= user.Last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.phoneNumber %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New user', new_user_path, class:"btn btn-secondary" %>

app/views/users/new.html.erb
<h1>New user</h1>
<br/>
<%= render 'form', user: @user %>
<br/>
<%= link_to 'Back', users_path, class:"btn btn-dark" %>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"> <%= @user.First_name %>  <%= @user.Last_name %></h1>
  <p class="lead">
	<%= @user.email %>|<%= @user.phoneNumber %>
  </p>
<br/>
  <hr class="my-4">
  <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-secondary" %>
  <%= link_to 'Back', users_path, class:"btn btn-secondary" %>
</div>